version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/mathieu/workspace/factuCabinet:/var/www/html
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    volumes:
      - /home/mathieu/workspace/factuCabinet:/var/www/html
